name: build

on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true

      - name: Build
        run: |
          docker build . # will run buildx
