name: release

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Tag name
        id: tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}

      - name: Build
        run: |
          docker build --tag ${{ secrets.DOCKER_REGISTRY }}/uni-verse/frontend:latest --tag ${{ secrets.DOCKER_REGISTRY }}/uni-verse/frontend:${{ steps.tag_name.outputs.TAG_NAME }} . # will run buildx
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/uni-verse/frontend:${{ steps.tag_name.outputs.TAG_NAME }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/uni-verse/frontend:latest
